- hosts: all
  become: yes
  tasks:
  - name: Installing containerd
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - sshpass
      update_cache: yes

  - name: Copy sshpass
    shell:
      cmd: sshpass -p "vagrant" scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no 172.16.16.100:/tmp/join-command /tmp/joincluster.sh 
    become_user: vagrant
  - name: Join the node to cluster
    command: /bin/sh /tmp/joincluster.sh
    