- hosts: all
  become: yes
  tasks:
  - name: Remove swapfile from /etc/fstab
    mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
    with_items:
        - swap
        - none
  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0
  
  - name: Disable firewall
    ufw:
      state: disabled
    
  - name: Enable sshd 
    lineinfile: dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication no' line='PasswordAuthentication yes' 
  
  - name: reload sshd
    systemd:
       name: sshd
       state: reloaded

  - name: Adding the module file
    copy:
      dest: "/etc/modules-load.d/containerd.conf"
      content: |
        overlay  
        br_netfilter
      mode: 0644
  
  - name: Add the module
    modprobe:
      name: "{{ item}}"
      state: present
    with_items:
      - overlay
      - br_netfilter
        
 
        
  # Set ip forwarding on in /proc and in the sysctl file and reload if necessary
  - name: Adding the sysctl entries
    sysctl:
      name: "{{ item }}"
      value: '1'
      sysctl_set: yes
      state: present
      reload: yes
    with_items:
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward
  #### Installation of containerd

  - name: Installing containerd
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - containerd
        - apt-transport-https
      update_cache: yes

  - name: Creation of container directory
    file:
      name: /etc/containerd
      state: directory
      recurse: yes

  - name: containerd config
    shell: 
      cmd: "containerd config default > /etc/containerd/config.toml"

  - name: Restarting containerd
    systemd:
      name: containerd
      state: restarted
      enabled: yes
  ######### Installing kubernetes

  - name: Adding the key
    apt_key:
      url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
      state: present
  - name: Adding the repo  
    apt_repository:
      repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
      state: present

  - name: Installing Kubernetes
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - kubelet=1.25.0-00 
        - kubeadm=1.25.0-00
        - kubectl=1.25.0-00

  - name: Enable and start kubelet
    systemd:
       name: kubelet
       state: started
       enabled: yes

  - name: Adding the hostnames
    copy:
      content: |
        172.16.16.100 kubemaster.example.com kubermaster 
        172.16.16.101 client1.example.com client1 
        172.16.16.102 client2.example.com client2 
      dest: "/etc/hosts"
      mode: 0644
